spring:
  application:
    name: sample
  profiles:
    active: dev
  config:
    import:
      - 'aws-parameterstore:'

normal-param: 'yml-defined'
secure-param: 'yml-defined-secure'
multiple-params:
  - 'yml-defined-param01'
  - 'yml-defined-param02'
  - 'yml-defined-param03'
